name: receitas_de_pao
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.

  #firebase
  # firebase_core: ^2.4.0
  # firebase_storage: ^11.0.7
  # cloud_firestore: ^4.2.0
  # firebase_analytics: ^10.0.7
  # firebase_auth: ^4.2.0
  # firebase_messaging: ^14.1.4
  # firebase_auth_platform_interface: ^6.4.0

  # google_mobile_ads: ^2.3.0
  # cupertino_icons: ^1.0.2
  # flutter_search_bar: ^2.1.0
  # provider: ^6.0.1
  # mask_text_input_formatter: ^2.0.0
  # email_validator: ^2.0.1
  # bloc: ^8.0.1
  # flutter_bloc: ^8.0.0
  # flutter_toggle_tab: ^1.1.7
  # image_picker: ^0.8.4+4    
  # carousel_slider: ^4.0.0
  # flutter_spinbox: ^0.8.0
  # bottom_drawer: ^0.0.4
  # uuid: ^3.0.5
  # google_fonts: ^2.2.0
  # share_plus: ^4.0.4
  # open_file: ^3.2.1
  # package_info_plus: ^1.3.0
  # flutter_image_compress: ^1.1.0
  # image_cropper: ^1.4.1
  # path_provider: ^2.0.8
  # intl: ^0.17.0
  # stack: ^0.0.1
  # flutter_secure_storage: ^7.0.0
  # flutter_launcher_icons: ^0.9.2
  # font_awesome_flutter: ^9.2.0
  # duration_picker: ^1.0.0
  # flutter_rating_bar: ^4.0.0
  # assets_audio_player: ^3.0.4+1
  # lottie: ^1.2.2
  # flutter_background_service: ^0.2.6
  # shared_preferences: ^2.0.13
  # flutter_local_notifications: ^9.4.0
  # chewie: ^1.3.2
  # video_player: ^2.3.0
  # youtube_player_flutter: ^8.0.0
  # http: ^0.13.4
  # web_scraper: ^0.1.4
  # flutter_staggered_grid_view: ^0.6.1
  # purchases_flutter: ^3.10.0
  # modal_bottom_sheet: ^2.0.1
  # sqflite: ^2.0.2+1
  # rate_my_app: ^1.1.2
  # decimal: ^2.2.0
  # currency_text_input_formatter: ^2.1.7
  # pdf: ^3.8.3
  # money_formatter: ^0.0.3
  # webview_flutter: ^3.0.4
  # url_launcher: ^6.1.5
  # indexed_list_view: ^2.0.2
  # diacritic: ^0.1.3
  # flutter_countdown_timer: ^4.1.0



  # flutter_localizations:
  #   sdk: flutter
  # flutter_email_sender: ^5.2.0
  # jiffy: ^5.0.0
  # circular_countdown_timer: ^0.2.3
  # android_alarm_manager_plus: ^3.0.1
  # flutter_native_timezone: ^2.0.0
  # audioplayers: ^4.1.0
  # pausable_timer: ^1.0.0+7

   #firebase
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.0
  firebase_messaging: ^14.1.4
  firebase_auth_platform_interface: ^6.4.0
  
  cupertino_icons: ^1.0.2
  flutter_search_bar: ^3.0.0
  google_mobile_ads: ^0.13.5
  provider: ^6.0.1
  mask_text_input_formatter: ^2.0.0
  email_validator: ^2.0.1
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  flutter_toggle_tab: ^1.1.7
  image_picker: ^0.8.4+4    
  carousel_slider: ^4.0.0
  #full_screen_image: ^1.0.2
  flutter_spinbox: ^0.8.0
  bottom_drawer: ^0.0.4
  im_stepper: ^0.1.3
  uuid: ^3.0.5
  google_fonts: ^2.2.0
  share_plus: ^4.0.4
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  flutter_image_compress: ^1.1.0
  image_cropper: ^1.4.1
  path_provider: ^2.0.8
  intl: ^0.17.0
  #stack: ^0.0.1
  flutter_secure_storage: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  google_sign_in: ^5.2.3
  font_awesome_flutter: ^9.2.0
  duration_picker: ^1.0.0
  flutter_rating_bar: ^4.0.0
  assets_audio_player: ^3.0.4+1
  lottie: ^1.2.2
  flutter_background_service: ^0.2.6
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.4.0
  chewie: ^1.3.2
  video_player: ^2.3.0
  youtube_player_flutter: ^8.0.0
  http: ^0.13.4
  web_scraper: ^0.1.4
  flutter_staggered_grid_view: ^0.6.1
  purchases_flutter: ^3.10.0
  modal_bottom_sheet: ^2.0.1
  sqflite: ^2.0.2+1
  rate_my_app: ^1.1.2
  decimal: ^2.2.0
  currency_text_input_formatter: ^2.1.7
  pdf: ^3.8.3
  money_formatter: ^0.0.3
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  indexed_list_view: ^2.0.2
  diacritic: ^0.1.3
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "lib/assets/logo.png"
  android: true
  ios: true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lib/assets/
    - lib/afiliados/receitas_de_sucesso/resources/
    - lib/afiliados/geladinhos_gourmet_danusa/resources/
    - lib/afiliados/brigadeiros_de_sucesso/resources/
    - lib/afiliados/curso_hamburguer_artesanal/resources/
    - lib/afiliados/desafio_19_dias/resources/
    - lib/afiliados/quinhentas_receitas_zero/resources/
    - lib/afiliados/cardapio_do_bebe/resources/
    - lib/afiliados/apostilas_master/resources/
    - lib/afiliados/quatrocentas_receitas_fit_lowcarb/resources/
    - lib/afiliados/receitas_para_bebes/resources/
    - lib/afiliados/receitas_funcionais/resources/
    - lib/afiliados/receitas_airfryer_55/resources/
    - lib/afiliados/curso_brigadeiro_gourmet/resources/
    - lib/afiliados/receitas_sucos_detox_53/resources/
    - lib/afiliados/curso_marmitaria_fit/resources/
    - lib/afiliados/receitas_bebes_1ano/resources/
    - lib/afiliados/marmita_fit/resources/
    - lib/afiliados/curso_salgadinhos_artesanais/resources/
    - lib/afiliados/curso_doces_finos_gourmet/resources/
    - lib/afiliados/especialista_bento_cake/resources/
    - lib/afiliados/secando_em_casa_30_dias/resources/
    - lib/afiliados/curso_quitanda_em_casa/resources/
    - lib/afiliados/arte_das_trancas_recheadas/resources/
    - lib/afiliados/marmita_fit_congelada/resources/
    - lib/afiliados/curso_bolo_caseirinho/resources/
    - lib/afiliados/curso_brownie_perfeito/resources/
    - lib/afiliados/curso_mestre_do_espetinho/resources/
    - lib/afiliados/curso_formacao_confeiteiros/resources/
    - lib/afiliados/copos_da_felicidade_lucrativos/resources/
    - lib/afiliados/curso_linguica_artesanal/resources/
    - lib/afiliados/curso_pizzaiolo/resources/
    - lib/afiliados/cachorro_quente_gourmet/resources/
    - lib/afiliados/curso_paes_caseiros_recheados/resources/

    
    - lib/afiliados_amazon/sanduicheira_grill_gourmet/resources/
    - lib/afiliados_amazon/kit_12_potes/resources/
    - lib/afiliados_amazon/jogo_utensilios_mm_house/resources/
    - lib/afiliados_amazon/porta_condimento_giratorio/resources/
    - lib/afiliados_amazon/mini_processador_alimentos/resources/
    - lib/afiliados_amazon/balanca_cozinha_inox/resources/
    - lib/afiliados_amazon/porta_mantimentos_bambu/resources/
    - lib/afiliados_amazon/fritadeira_airfryer/resources/
    - lib/afiliados_amazon/liquidificador_turbo/resources/
    - lib/afiliados_amazon/kit_4_potes/resources/
    - lib/afiliados_amazon/panela_pressao_eletrica/resources/
    - lib/afiliados_amazon/conjunto_utensilios_lumai/resources/
    - lib/afiliados_amazon/garrafa_termica_nordica/resources/
    - lib/afiliados_amazon/cortador_legumes_multifuncional/resources/
    - lib/afiliados_amazon/jogo_facas_tramontina/resources/
    - lib/afiliados_amazon/conjunto_medidores_inox/resources/
    - lib/afiliados_amazon/kit_3_tabuas/resources/
    - lib/afiliados_amazon/escorredor_de_pia_auto_sustentavel/resources/
    - lib/afiliados_amazon/panela_pressao_tramontina/resources/
    - lib/afiliados_amazon/mixer_alimentos/resources/
    - lib/afiliados_amazon/faqueiro_aco_inox/resources/
    - lib/afiliados_amazon/tapioqueira_tapy/resources/
    - lib/afiliados_amazon/escorredor_loucas_metaltru/resources/
    - lib/afiliados_amazon/copo_termico_stanley/resources/
    - lib/afiliados_amazon/afiador_facas_mor/resources/
    - lib/afiliados_amazon/torradeira_electrolux/resources/
    - lib/afiliados_amazon/fatiador_legumes_multifuncional/resources/
    - lib/afiliados_amazon/jogo_3_peneiras/resources/
    - lib/afiliados_amazon/ralador_coletor_brinox/resources/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
